<?PHP
$query="mssql_query";
	$fetch_array="mssql_fetch_array";
	$close="mssql_close";
	$connect="mssql_connect";
	$select_db="mssql_select_db";
	$free_result="mssql_free_result";
	$num_rows="mssql_num_rows";
	$num_fields="mssql_num_fields";
	$field_name="mssql_field_name";

	$almacen=19;
	$almacenadmin=18;
	$almacenopera=19;
	$almacenconsulta=20;
	$rrhh=21;
	$rrhhadmin=22;
	$inventarioadmin=23;
	$inventarioopera=24;
	$inventarioconsulta=25;
	$uipadmin=26;
	$uipopera=28;
	$uipconsulta=28;
	$formularioadmin=29;
	$biblioteca=30;
	$vehiculos=23;
	$empresa="MINISTERIO DE ECONOMIA";
	$bodega=1;
	$presupuesto = 16;
	$visitantes=31;
        
              
        $almacenadministrador=33;
        $almacenaprobacion=34;
        $almacenautorizacion=35;
        $almacendespacho=36;        
        $almaceningreso=37;
        $almacendirecta=38;
        $almacenrequisicion=39;
        $almacen=40;
        $almacencsuario=41;
        $almacencatalogos=42;

	//expedientes
	$expedopera=43;
	//horas extras
	$reloj_marcaje=44;
	$comunicacion=45;
	$cafeteria=46;
	$sitrame=47;
	$sigemineco=48;
	$rrhh2012=49;
	$bitacora=50;
	$bitacora2=51;	
	$bgerencia=52;	
	$bsecretaria=53;
	$bdespacho=54;
?>